server {
  listen 443 ssl;
  server_name localhost;

  ssl_certificate /etc/nginx/certs/webui.crt;
  ssl_certificate_key /etc/nginx/certs/webui.key;

  location / {
    proxy_pass http://webui:3000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection keep-alive;
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }

  location /api/config/ {
    proxy_pass https://configapi:5000/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /api/data/ {
    proxy_pass https://dataapi:5001/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /api/report/ {
    proxy_pass https://reportapi:5002/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /api/identity/ {
    proxy_pass https://identityapi:5003/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
